<?php
// Centralized config loading
require_once 'db_connect.php'; // This should load config.php and set $admin_email

if (!isset($admin_email)) {
    die('Admin email is not set. Please check your config.php.');
}

// Function to analyze each log line
function analyze_log_line($line) {
    // List of known bots, cloud/VPS, PH IP ranges
    $bots = ['Googlebot', 'GoogleOther', 'Bingbot', 'meta-externalagent', 'Scrapy', 'CMS-Checker', 'Facebook'];
    $clouds = ['Amazon', 'Google Cloud', 'DigitalOcean', 'Colocation', 'Leaseweb', 'ITL-Bulgaria', 'Linode', 'Vultr', 'Psychz', 'Cloud', 'AWS', 'Seychelles'];
    $ph_ips = ['180.232.', '124.209.', '119.93.', '112.198.', '121.54.', '49.144.', '103.']; // Add more PH prefixes if needed

    if (!preg_match('/IP: ([^ ]+) - UA: (.*)$/', $line, $m)) return ['status'=>'Unknown','desc'=>$line];
    $ip = $m[1];
    $ua = $m[2];

    foreach ($ph_ips as $prefix) {
        if (strpos($ip, $prefix) === 0) return ['status'=>'Likely Human','desc'=>$line];
    }
    foreach ($bots as $b) {
        if (stripos($ua, $b) !== false) return ['status'=>'Bot','desc'=>$line];
    }
    foreach ($clouds as $c) {
        if (stripos($ua, $c) !== false) return ['status'=>'Suspicious','desc'=>$line];
    }
    if (stripos($ua, 'Mozilla') === false || $ua === 'N/A') return ['status'=>'Suspicious','desc'=>$line];

    return ['status'=>'Suspicious','desc'=>$line];
}

// Email send function
function send_alert($to, $subject, $message) {
    $headers = "From: noreply@yourdomain.com\r\n";
    $headers .= "Content-Type: text/plain; charset=utf-8\r\n";
    return mail($to, $subject, $message, $headers);
}

// Analyze log file
$logfile = __DIR__ . '/counter_log.txt';
if (!file_exists($logfile)) die('counter_log.txt not found');
$lines = file($logfile);
$suspicious = [];
$report = '';

foreach ($lines as $line) {
    $result = analyze_log_line(trim($line));
    $report .= "[{$result['status']}] {$result['desc']}\n";
    if ($result['status'] === 'Suspicious') {
        $suspicious[] = $result['desc'];
    }
}

// Email alert if there are suspicious visits
if (!empty($suspicious)) {
    $subject = "ALERT: Suspicious Access Detected";
    $message = "May suspicious access detected sa iyong site:\n\n" . implode("\n", $suspicious) . "\n\n---\nGenerated by analyzer script.";
    send_alert($admin_email, $subject, $message);
}

echo "<pre>$report</pre>";
?>
